ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "say Server will be shutting down in 15 minutes for maintenance.  There will be 15 minutes downtime.")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")
Sleep(300000)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "say Server shutting down in 10 minutes.  Please log out before shutdown.")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")
Sleep(300000)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "say Server shutting down in 5 minutes.  Please log out before shutdown.")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")
Sleep(300000)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "say Server shutting down in 1 minute.  There will be 15 minutes downtime.")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")
Sleep(500)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "say Please log out now.")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")
Sleep(60000)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "say Server shutting down in 10...")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")
Sleep(1000)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "say 9")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")
Sleep(1000)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "say 8")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")
Sleep(1000)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "say 7")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")
Sleep(1000)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "say 6")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")
Sleep(1000)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "say 5")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")
Sleep(1000)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "say 4")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")
Sleep(1000)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "say 3")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")
Sleep(1000)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "say 2")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")
Sleep(1000)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "say 1")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")
Sleep(1000)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "stop")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")

Sleep(60000)
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "exit")
ControlSend("C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe", "", "", "{Enter}")